import type { ProtocolSchema } from './schema.js'

function generateHeader(): string {
  return [
    '// AUTO-GENERATED BY @swiftstatetree/sdk codegen.',
    '// Do not edit this file directly.',
    '',
  ].join('\n')
}

/**
 * Generate the contents of schema.ts.
 */
export function generateSchemaTs(schema: ProtocolSchema): string {
  const lines: string[] = []

  lines.push(generateHeader())
  lines.push(`export const SCHEMA_VERSION = ${JSON.stringify(schema.version)} as const`)
  lines.push('')

  const landIDs = Object.keys(schema.lands)
  lines.push(`export const LAND_IDS = ${JSON.stringify(landIDs)} as const`)
  lines.push('export type LandID = (typeof LAND_IDS)[number]')
  lines.push('')

  // Build per-land id collections.
  const actionIdsByLand: Record<string, string[]> = {}
  const clientEventIdsByLand: Record<string, string[]> = {}
  const serverEventIdsByLand: Record<string, string[]> = {}

  for (const [landID, landDef] of Object.entries(schema.lands)) {
    actionIdsByLand[landID] = Object.keys(landDef.actions ?? {})
    clientEventIdsByLand[landID] = Object.keys(landDef.clientEvents ?? {})
    serverEventIdsByLand[landID] = Object.keys(landDef.events ?? {})
  }

  lines.push('export const ACTION_IDS = {')
  for (const landID of landIDs) {
    const ids = actionIdsByLand[landID] ?? []
    lines.push(`  ${JSON.stringify(landID)}: ${JSON.stringify(ids)} as const,`)
  }
  lines.push('} as const')
  lines.push('export type AnyActionID = (typeof ACTION_IDS)[LandID][number]')
  lines.push('export type ActionIDFor<L extends LandID> = (typeof ACTION_IDS)[L][number]')
  lines.push('')

  lines.push('export const CLIENT_EVENT_IDS = {')
  for (const landID of landIDs) {
    const ids = clientEventIdsByLand[landID] ?? []
    lines.push(`  ${JSON.stringify(landID)}: ${JSON.stringify(ids)} as const,`)
  }
  lines.push('} as const')
  lines.push('export type AnyClientEventID = (typeof CLIENT_EVENT_IDS)[LandID][number]')
  lines.push('export type ClientEventIDFor<L extends LandID> = (typeof CLIENT_EVENT_IDS)[L][number]')
  lines.push('')

  lines.push('export const SERVER_EVENT_IDS = {')
  for (const landID of landIDs) {
    const ids = serverEventIdsByLand[landID] ?? []
    lines.push(`  ${JSON.stringify(landID)}: ${JSON.stringify(ids)} as const,`)
  }
  lines.push('} as const')
  lines.push('export type AnyServerEventID = (typeof SERVER_EVENT_IDS)[LandID][number]')
  lines.push('export type ServerEventIDFor<L extends LandID> = (typeof SERVER_EVENT_IDS)[L][number]')
  lines.push('')

  return lines.join('\n')
}

