// AUTO-GENERATED BY @swiftstatetree/sdk codegen.
// Do not edit this file directly.

export type BuyUpgradeAction = { upgradeID: string }
export type BuyUpgradeResponse = { newCookies: number; newCookiesPerSecond: number; success: boolean; upgradeLevel: number }
export type ClickCookieEvent = { amount: number }
export type CookieGameState = { players: { [key: string]: CookiePlayerPublicState }; privateStates: { [key: string]: CookiePlayerPrivateState }; ticks: number; totalCookies: number }
export type CookiePlayerPrivateState = { totalClicks: number; upgrades: { [key: string]: number } }
export type CookiePlayerPublicState = { cookies: number; cookiesPerSecond: number; name: string }
export type StateDiff = { patches: { op: string; path: string; value?: { [key: string]: any } }[] }
