// AUTO-GENERATED BY @swiftstatetree/sdk codegen.
// Do not edit this file directly.

export const SCHEMA_VERSION = "0.1.0" as const

export const LAND_IDS = ["demo-game"] as const
export type LandID = (typeof LAND_IDS)[number]

export const ACTION_IDS = {
  "demo-game": ["BuyUpgrade"] as const,
} as const
export type AnyActionID = (typeof ACTION_IDS)[LandID][number]
export type ActionIDFor<L extends LandID> = (typeof ACTION_IDS)[L][number]

export const CLIENT_EVENT_IDS = {
  "demo-game": ["ClickCookie"] as const,
} as const
export type AnyClientEventID = (typeof CLIENT_EVENT_IDS)[LandID][number]
export type ClientEventIDFor<L extends LandID> = (typeof CLIENT_EVENT_IDS)[L][number]

export const SERVER_EVENT_IDS = {
  "demo-game": [] as const,
} as const
export type AnyServerEventID = (typeof SERVER_EVENT_IDS)[LandID][number]
export type ServerEventIDFor<L extends LandID> = (typeof SERVER_EVENT_IDS)[L][number]
