// AUTO-GENERATED BY @swiftstatetree/sdk codegen.
// Do not edit this file directly.

import type { BuyUpgradeAction, BuyUpgradeResponse, ClickCookieEvent, CookieGameState } from '../defs'

export const LAND_TYPE = "demo-game" as const

export type LandState = CookieGameState

export interface ActionPayloads {
  buyUpgrade: BuyUpgradeAction
}

export interface ActionResponses {
  buyUpgrade: BuyUpgradeResponse
}

export type ActionName = keyof ActionPayloads

export interface ClientEventPayloads {
  clickCookie: ClickCookieEvent
}

export type ClientEventName = keyof ClientEventPayloads

export interface ServerEventPayloads {
}

export type ServerEventName = keyof ServerEventPayloads

export type Actions = {
  [K in ActionName]: (payload: ActionPayloads[K]) => Promise<ActionResponses[K]>
}

export type ClientEvents = {
  [K in ClientEventName]: (payload: ClientEventPayloads[K]) => void
}

export type ServerEventSubscriptions = {
  [K in ServerEventName]: (handler: (payload: ServerEventPayloads[K]) => void) => () => void
}
