// Sources/SwiftStateTree/Sync/PatchableState.swift

import Foundation

/// Protocol for state types that support incremental patch recording.
///
/// Types conforming to this protocol can receive path context injection
/// from parent containers (like `ReactiveDictionary`) to enable
/// automatic patch recording during mutations.
///
/// This protocol is automatically conformed by `@StateNodeBuilder` macro.
public protocol PatchableState {
    /// The JSON Pointer path to this state node from the root.
    /// Injected by parent container during access.
    var _$parentPath: String { get set }
    
    /// Reference to the shared patch recorder.
    /// Injected by parent container during access.
    var _$patchRecorder: PatchRecorder? { get set }
    
    /// Propagate `_$patchRecorder` and `_$parentPath` to child fields
    /// that also conform to `PatchableState` (e.g., `ReactiveDictionary`,
    /// nested `StateNodeProtocol` types).
    ///
    /// This method is automatically generated by the `@StateNodeBuilder` macro.
    /// For non-macro types (like `ReactiveDictionary`), the default no-op
    /// implementation is sufficient since they have no nested PatchableState children.
    mutating func _$propagatePatchContext()
}

// MARK: - Default Implementation

extension PatchableState {
    /// Default no-op implementation for types without nested PatchableState children.
    public mutating func _$propagatePatchContext() {
        // No-op: override in macro-generated code for types with nested children.
    }
}
