#!/usr/bin/env bash
set -euo pipefail

# Merge all docs/**/*.zh-TW.md into a single markdown file.
# Each merged section includes the source file path.
#
# Usage:
#   ./Tools/merge-docs-zh-TW.sh [output_path]
#
# Default output:
#   docs/ALL.zh-TW.md

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="${ROOT_DIR}/docs"
OUT_PATH="${1:-${DOCS_DIR}/ALL.zh-TW.md}"

export ROOT_DIR DOCS_DIR OUT_PATH

python3 - <<'PY'
from __future__ import annotations

import datetime as dt
import os
from pathlib import Path

root_dir = Path(os.environ["ROOT_DIR"])
docs_dir = Path(os.environ["DOCS_DIR"])
out_path = Path(os.environ["OUT_PATH"])

if not docs_dir.exists() or not docs_dir.is_dir():
    raise SystemExit(f"docs directory not found: {docs_dir}")

files = sorted(p for p in docs_dir.rglob("*.zh-TW.md") if p.is_file())
out_rel = out_path.relative_to(root_dir) if out_path.is_absolute() else out_path

# Avoid self-inclusion if output is under docs/.
try:
    out_abs = out_path.resolve()
    files = [p for p in files if p.resolve() != out_abs]
except FileNotFoundError:
    # If out_path doesn't exist yet, resolve() can still work, but keep safe fallback.
    pass

out_path.parent.mkdir(parents=True, exist_ok=True)

generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def read_text(p: Path) -> str:
    # Prefer UTF-8; strip BOM if present.
    text = p.read_text(encoding="utf-8")
    if text.startswith("\ufeff"):
        text = text.lstrip("\ufeff")
    return text.rstrip() + "\n"

lines: list[str] = []
lines.append("<!--")
lines.append("  AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.")
lines.append(f"  Generated by: Tools/merge-docs-zh-TW.sh")
lines.append(f"  Source: {docs_dir.relative_to(root_dir)}")
lines.append(f"  Generated at (UTC): {generated_at}")
lines.append("-->")
lines.append("")
lines.append("# docs/ 中文文件合併版（zh-TW）")
lines.append("")
lines.append(f"- **輸出檔**: `{out_rel.as_posix()}`")
lines.append(f"- **來源目錄**: `docs/`")
lines.append(f"- **產生時間（UTC）**: `{generated_at}`")
lines.append("")
lines.append("## 目錄")
lines.append("")

toc_entries: list[tuple[str, str]] = []
for idx, p in enumerate(files, start=1):
    rel = p.relative_to(root_dir).as_posix()
    anchor = f"file-{idx:04d}"
    toc_entries.append((rel, anchor))

for rel, anchor in toc_entries:
    lines.append(f"- [{rel}](#{anchor})")

for (rel, anchor), p in zip(toc_entries, files):
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"<a id=\"{anchor}\"></a>")
    lines.append(f"## `{rel}`")
    lines.append("")
    lines.append(read_text(p))

out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
print(f"Wrote: {out_path}")
print(f"Files merged: {len(files)}")
PY

