// Sources/SwiftStateTree/StateTree/StateNodeProtocol.swift

/// Protocol that marks a type as a StateNode.
/// 
/// StateNode is a node in the state tree that can be nested recursively.
/// Types conforming to this protocol must:
/// - Be marked with `@StateNodeBuilder` macro (required for compile-time validation and code generation)
/// - Have stored properties marked with `@Sync` (for synchronization) or `@Internal` (for server-only use)
/// - Computed properties are automatically skipped from validation
/// - Conform to `Sendable` for thread-safe usage
///
/// The `@StateNodeBuilder` macro automatically generates:
/// - `getSyncFields()` method implementation
/// - `validateSyncFields()` method implementation
/// - `snapshot(for:)` method implementation
/// - `broadcastSnapshot()` method implementation (for efficient broadcast snapshot generation)
///
/// Example:
/// ```swift
/// @StateNodeBuilder
/// struct GameStateRootNode: StateNodeProtocol {
///     @Sync(.broadcast)
///     var players: [PlayerID: PlayerStateNode] = [:]
///     
///     @Sync(.serverOnly)
///     var hiddenDeck: [Card] = []
///     
///     @Internal
///     var lastProcessedTimestamp: Date = Date()
///     
///     var totalPlayers: Int {
///         players.count
///     }
/// }
/// ```
public protocol StateNodeProtocol: Sendable {
    /// Get all fields marked with @Sync in this StateNode
    /// 
    /// Returns an array of `SyncFieldInfo` containing the name and policy type
    /// of each field marked with `@Sync`.
    ///
    /// This method is automatically generated by the `@StateNodeBuilder` macro.
    ///
    /// Example:
    /// ```swift
    /// let fields = gameState.getSyncFields()
    /// // Returns: [SyncFieldInfo(name: "players", policyType: "broadcast"), ...]
    /// ```
    func getSyncFields() -> [SyncFieldInfo]
    
    /// Validate that all stored properties have @Sync or @Internal markers
    /// 
    /// Returns `true` if all stored properties are marked with `@Sync` or `@Internal`.
    /// Since validation happens at compile time with the `@StateNodeBuilder` macro,
    /// this method always returns `true` for macro-generated implementations.
    ///
    /// This method is automatically generated by the `@StateNodeBuilder` macro.
    ///
    /// Validation rules (enforced at compile time):
    /// - ✅ `@Sync` marked fields: require synchronization
    /// - ✅ `@Internal` marked fields: server-only use, skip validation
    /// - ✅ Computed properties: automatically skipped
    /// - ❌ Unmarked stored properties: compile-time error
    func validateSyncFields() -> Bool
    
    /// Generate a snapshot of the StateNode for a specific player or broadcast fields only
    /// 
    /// Returns a `StateSnapshot` containing only the fields that should be
    /// synchronized to the specified player, according to their `@Sync` policies.
    ///
    /// - Parameter playerID: The player ID to generate the snapshot for. If `nil`, only broadcast fields are included.
    ///
    /// This method is automatically generated by the `@StateNodeBuilder` macro.
    /// It avoids runtime reflection by directly accessing `@Sync` fields at compile time.
    ///
    /// Example:
    /// ```swift
    /// let snapshot = gameState.snapshot(for: playerID)
    /// // Returns: StateSnapshot with filtered fields based on sync policies
    /// 
    /// let broadcastSnapshot = gameState.snapshot(for: nil)
    /// // Returns: StateSnapshot with only broadcast fields
    /// ```
    func snapshot(for playerID: PlayerID?) throws -> StateSnapshot
    
    /// Generate a broadcast snapshot (for efficient broadcast snapshot generation)
    ///
    /// Returns a `StateSnapshot` containing only broadcast fields, without needing a player ID.
    /// This method is optimized for broadcast snapshot generation and avoids runtime reflection.
    ///
    /// This method is automatically generated by the `@StateNodeBuilder` macro.
    /// It directly accesses broadcast fields at compile time, avoiding Mirror reflection.
    ///
    /// Example:
    /// ```swift
    /// let broadcastSnapshot = gameState.broadcastSnapshot()
    /// // Returns: StateSnapshot with only broadcast fields (players, round, turn, etc.)
    /// ```
    func broadcastSnapshot() throws -> StateSnapshot
}

