// Sources/SwiftStateTree/StateTree/StateTreeProtocol.swift

/// Protocol that marks a type as a StateTree.
/// 
/// StateTree is the single source of truth for domain state.
/// Types conforming to this protocol must:
/// - Be marked with `@StateTreeBuilder` macro (required for compile-time validation and code generation)
/// - Have stored properties marked with `@Sync` (for synchronization) or `@Internal` (for server-only use)
/// - Computed properties are automatically skipped from validation
/// - Conform to `Sendable` for thread-safe usage
///
/// The `@StateTreeBuilder` macro automatically generates:
/// - `getSyncFields()` method implementation
/// - `validateSyncFields()` method implementation
/// - `snapshot(for:)` method implementation
///
/// Example:
/// ```swift
/// @StateTreeBuilder
/// struct GameStateTree: StateTreeProtocol {
///     @Sync(.broadcast)
///     var players: [PlayerID: PlayerState] = [:]
///     
///     @Sync(.serverOnly)
///     var hiddenDeck: [Card] = []
///     
///     @Internal
///     var lastProcessedTimestamp: Date = Date()
///     
///     var totalPlayers: Int {
///         players.count
///     }
/// }
/// ```
public protocol StateTreeProtocol: Sendable {
    /// Get all fields marked with @Sync in this StateTree
    /// 
    /// Returns an array of `SyncFieldInfo` containing the name and policy type
    /// of each field marked with `@Sync`.
    ///
    /// This method is automatically generated by the `@StateTreeBuilder` macro.
    ///
    /// Example:
    /// ```swift
    /// let fields = gameState.getSyncFields()
    /// // Returns: [SyncFieldInfo(name: "players", policyType: "broadcast"), ...]
    /// ```
    func getSyncFields() -> [SyncFieldInfo]
    
    /// Validate that all stored properties have @Sync or @Internal markers
    /// 
    /// Returns `true` if all stored properties are marked with `@Sync` or `@Internal`.
    /// Since validation happens at compile time with the `@StateTreeBuilder` macro,
    /// this method always returns `true` for macro-generated implementations.
    ///
    /// This method is automatically generated by the `@StateTreeBuilder` macro.
    ///
    /// Validation rules (enforced at compile time):
    /// - ✅ `@Sync` marked fields: require synchronization
    /// - ✅ `@Internal` marked fields: server-only use, skip validation
    /// - ✅ Computed properties: automatically skipped
    /// - ❌ Unmarked stored properties: compile-time error
    func validateSyncFields() -> Bool
    
    /// Generate a snapshot of the StateTree for a specific player
    /// 
    /// Returns a `StateSnapshot` containing only the fields that should be
    /// synchronized to the specified player, according to their `@Sync` policies.
    ///
    /// This method is automatically generated by the `@StateTreeBuilder` macro.
    /// It avoids runtime reflection by directly accessing `@Sync` fields at compile time.
    ///
    /// Example:
    /// ```swift
    /// let snapshot = gameState.snapshot(for: playerID)
    /// // Returns: StateSnapshot with filtered fields based on sync policies
    /// ```
    func snapshot(for playerID: PlayerID) throws -> StateSnapshot
}

