// Sources/SwiftStateTree/StateTree/StateTree.swift

import Foundation

/// Information about a sync field in a StateNode
public struct SyncFieldInfo: Sendable {
    /// The name of the field
    public let name: String
    
    /// The sync policy applied to this field
    public let policyType: String
    
    public init(name: String, policyType: String) {
        self.name = name
        self.policyType = policyType
    }
}

// All methods are now generated by @StateNodeBuilder macro
// No runtime reflection implementation needed

